### PR TITLE
Theme fixes and improvements

### LINKED ISSUE #300: The go-to-top button on mobile moves up and down as I scroll up and down
Is it possible to have it fixed in one spot?  I can't seem to get a good recording of this because it does it most on my own phone...

### LINKED ISSUE #306: Add search box (with search query) to top of search results page?
I've been fixing broken links and using the frontend search quite a bit. I feel like it would be useful to include a search box and the search query on the search results, so queries can be edited. Currently the user must click search in the header, then re-enter query to search again.

### PR DESCRIPTION
**Pull request by thetwopct**
In this update: 

Adding accepted dates to projects link title, ref #261
Updating pagination styles to match other links, ref #328
Adding admin message to LF MU if the plugin is not installed, ref #284
Adding checks for including LF MU files, ref #284
Fixing admin header search input, closes #306
Fix closing div outside if statement in header
Adding minimum PHP and WP versions to style.css
Updating back to top position, changing fade in/out method, closes #300

### CODE REVIEW

**Comment by cjyabraham** [comment]
I think the pagination styles work well!

File: web/wp-content/themes/lf-theme/includes/shortcode-projects.php [hunk 1]
```diff
@@ -56,6 +56,8 @@ function add_projects_shortcode( $atts ) {
 
 			$external_url = get_post_meta( get_the_ID(), 'lf_project_external_url', true );
 
+			$date_accepted = get_post_meta( get_the_ID(), 'lf_project_date_accepted', true ) ? ' (accepted to CNCF on ' . gmdate( 'm/d/Y', strtotime( get_post_meta( get_the_ID(), 'lf_project_date_accepted', true ) ) ) . ')' : '';
```
Comment (cjyabraham) [inline web/wp-content/themes/lf-theme/includes/shortcode-projects.php:59]: Any objections to using 'n/j/Y' instead of 'm/d/Y' for date format?

Comment (thetwopct) [reply web/wp-content/themes/lf-theme/includes/shortcode-projects.php]: I've updated it
